# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

# Plugins
plugins:
  - github-pages

whitelist:
  - github-pages

# Elements
crust_tastic:
  stylesheets:
    - url: assets/css/style.css
    - url: assets/css/highlight.css
    - url: https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap

# Optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
