# Site Info
title: Regulad's Crust-Tastic Jekyll Theme
name: Regulad's Crust-Tastic Jekyll Theme
author: regulad

# Plugins
plugins:
  - github-pages

# Theme
remote_theme: regulad/crust-tastic@main
navigation: true
github_info: true
