# Jekyll
remote_theme: regulad/crust-tastic@main

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

crust_tastic:
  header:
    title: true
    github_desc: true
  footer:
    github_link: true

# Plugins
plugins:
  - github-pages

whitelist:
  - github-pages

# Optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed

# crust-tastic
crust_tastic:
  favicon: false # Controls the favicon of the webpage. If you would like to use a custom path, substitute truthy/falsey with /path/to/favicon, otherwise it will use the root of the site.
  gtag: false # Controls site gtag
  header:
    title: true # Controls Title
    github_desc: true # Controls the GitHub description.
    pin: true # Pins header to the top of the page.
  footer:
    navigation: false # See below.
    github_link: true # Controls the GitHub link at the bottom of the page.
    google_translate: true # Controls google translate
    jump: true # Controls displaying the "Jump to top of page button."
