# Site Info
title: Regulad's Crust-Tastic Jekyll Theme
name: Regulad's Crust-Tastic Jekyll Theme
author: regulad

# Jekyll
remote_theme: regulad/crust-tastic@v1.0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

# Plugins
plugins:
  - github-pages

whitelist:
  - github-pages

# Elements
github_info: true
gtranslate: true

# Optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
