# Jekyll
remote_theme: regulad/crust-tastic@main

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

crust_tastic:
  header:
    title: true
    github_desc: true
  footer:
    github_link: true

# Plugins
plugins:
  - github-pages

whitelist:
  - github-pages

# Optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed

# crust-tastic
crust_tastic:
  favicon: /assets/favicon
  header:
    title: true
    github_desc: true
  footer:
    github_link: true
