# Site Info
title: A Site Built Using Regulad's Crust-Tastic Jekyll Theme
author: regulad

# Theme
remote_theme: regulad/crust-tastic@v2.0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

# Plugins
plugins:
  - github-pages

whitelist:
  - github-pages

# Elements
crust_tastic:
  github_info: true
  google_translate: true
  skin: stock

# Optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

sass:
  style: compressed
